apps/sail_frontend_app_app/sail_frontend_app/urls.py
"""
Use sail_frontend_app as the namespace when including those urls inside another urlpatterns:

    urlpatterns = patterns('',
        ...
        url(r'^app/', include('sail_frontend_app.urls', namespace='sail_frontend_app'))
    )
"""

from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'sail_frontend_app/login.html', 'redirect_field_name': None}, name='login'),
    url(r'^logout/$', 'logout', {'template_name': 'sail_frontend_app/logout.html', 'redirect_field_name':None}, name='logout'),
    (r'^$', TemplateView.as_view(template_name="sail_frontend_app/index.html")),
)

apps/sail_frontend_app_app/sail_frontend_app/views.py
# Create your views here.

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/base.html
{% load url from future %}
{% load static from staticfiles %}
<!DOCTYPE html>
<html>

    <head>
    {% block head %}

        {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        {% endblock %}

        <title>{% block title %}Sail App{% endblock %}</title>

        {% block style %}
        {% block bootstrap_theme %}
        <link rel="stylesheet" type="text/css" href="{% static "sail_frontend_app/css/bootstrap.css" %}"/>
        <link rel="stylesheet" type="text/css" href="{% static "sail_frontend_app/css/bootstrap-tweaks.css" %}"/>
        {% endblock %}
        <link rel="stylesheet" type="text/css" href="{% static "sail_frontend_app/css/default.css" %}"/>
        {% endblock %}
    {% endblock %}
    </head>

    <body class="container">

        <div class="container-fluid" style="margin-top: 30px">
            <div class="row-fluid">
                <div class="well" style="width: 320px; margin-left: auto; margin-right: auto">
                    <div class="row-fluid">
                        <div>
                            {% block branding %}<h3 style="margin: 0 0 20px;">Sail</h3>{% endblock %}
                        </div>
                    </div>{# <!-- /row fluid --> #}
        
                    {% block content %}
                    {# <!-- login/logout content goes here --> #}
                    {% endblock %}
                    
                </div>{# <!--/.well--> #}
            </div>{# <!-- /.row-fluid --> #}
        </div>{# <!-- /.container-fluid --> #}
    </body>
</html>

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/calendar_tab.html
{# <!-- Two panes layout --> #}
<div class="row-fluid">
    {# <!-- Calendar --> #}
    <div class="span6">
        <div ng-controller="CalendarCtrl">
            <div ui-calendar="uiConfig.calendar" ng-model="eventSources" calendar="mainCalendar"></div>
        </div>
    </div>
    {# <!-- Selected reservation details --> #}
    <div class="span6">
        <div ng-controller="ReservationDetailCtrl">
        
            <div class="row">
                <div class="span8 offset4">
                    <a class="btn btn-primary" href="#" ng-click="open()"><i class="icon-pencil"></i> Edit Reservation</a>
                </div>
            </div>
            
            {% verbatim %}
            <dl class="dl-horizontal">
                <dt>Name</dt>
                <dd>{{data.reservation.name}}</dd>

                <dt>Description</dt>
                <dd>{{data.reservation.description}}</dd>
                
                <dt>Amount</dt>
                <dd>${{data.reservation.price}}</dd>
                
                <dt>From</dt>
                <dd>{{data.reservation.date_from | date:'MM/dd/yyyy'}}</dd>
                
                <dt>To</dt>
                <dd>{{data.reservation.date_to | date:'MM/dd/yyyy'}}</dd>
            </dl>
            {% endverbatim %}
            
        </div>
    </div>
</div>

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/content.html
<div>
    <div ng-show="tab.display=='reservation'">
        {% include "sail_frontend_app/reservations_tab.html" %}
    </div>
    <div ng-show="tab.display=='property'">
        {% include "sail_frontend_app/properties_tab.html" %}
    </div>
    <div ng-show="tab.display=='calendar'">
        {% include "sail_frontend_app/calendar_tab.html" %}
    </div>
    <div ng-show="tab.display=='report'">
        {% include "sail_frontend_app/reports_tab.html" %}
    </div>
</div>

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/dummy_app.html
{% extends "sail_frontend_app/base.html" %}

{% block content %}
<div class="row-fluid">
    <div>
    {% if user.is_authenticated %}
        <p><span>You are now logged in Sail.</span></p>
        <p><a href="{% url 'sail_frontend_app:logout' %}">Logout</a></p>
    {% else %}
        <p><span>You are not logged in Sail.</span></p>
        <p><a href="{% url 'sail_frontend_app:login' %}">Login</a></p>
    {% endif %}
    </div>
</div>
{% endblock %}

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/index.html
<!doctype html>
{% comment %}
The following classes are used with Modernizr.
They help knowing which browser is used, which features are available and whether JavaScript is disabled.
http://stackoverflow.com/questions/6724515/what-is-the-purpose-of-the-html-no-js-class

The first entry is to prevent IE from blocking when loading files if conditional comments are used on the page:
http://www.phpied.com/conditional-comments-block-downloads/
{% endcomment %}
<!--[if IE]><![endif]-->
<!--[if lt IE 7]>      <html lang="en-US" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-US" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-US" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-US" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        {# IE: use latest rendering method or Google Chrome Frame #}
        <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
        <title>Sail App</title>
        <meta name="viewport" content="width=device-width">
        {# <!-- Place favicon.ico and apple-touch-icon.png in the root directory --> #}

        {# <!-- build:css({.tmp,app}) styles/main.css --> #}
        <link rel="stylesheet" href="styles/bootstrap.css">
        <link rel="stylesheet" href="styles/main.css">
        {# <!-- endbuild --> #}
        <link rel='stylesheet' type='text/css' href='bower_components/fullcalendar/fullcalendar.css' />
        <link rel='stylesheet' type='text/css' href='bower_components/jqplot-bower/dist/jquery.jqplot.css' />
    </head>
    
    {% if user.is_authenticated %}
    <body ng-app="sailFrontendApp" ng-show="true" style="display:none">
        {# <!-- Navigation bar --> #}
        {% include "sail_frontend_app/navigation_bar.html" %}
        
        {# <!-- Content --> #}
        {% include "sail_frontend_app/content.html" %}
        
        {# <!-- Templates --> #}
        {% include "sail_frontend_app/templates/templates.html" %}

        {# <!-- Scripts --> #}
        {% include "sail_frontend_app/scripts.html" %}

    {% else %}
    <body>
        <p><span>You are not logged in Sail.</span></p>
        <p><a href="{% url 'sail_frontend_app:login' %}">Login</a></p>
    {% endif %}
    </body>
</html>

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/login.html
{% extends "sail_frontend_app/login_base.html" %}

{% block content %}
<div class="row-fluid">
    <div>
        <form action="{% url 'sail_frontend_app:login' %}" class=" form-inline" method="post">
            {% csrf_token %}
            <div id="div_id_username" class="clearfix control-group">
                <div class="controls">
                    <Label class="span4">Username:</label>
                    <input style="height: 25px" type="text" name="username" maxlength="100" autocapitalize="off" autocorrect="off" class="textinput textInput" id="id_username">
                </div>
            </div>
            <div id="div_id_password" class="clearfix control-group">
                <div class="controls">
                    <Label class="span4">Password:</label>
                    <input style="height: 25px" type="password" name="password" maxlength="100" autocapitalize="off" autocorrect="off" class="textinput textInput" id="id_password">
                </div>
            </div>
            <div class="form-actions-no-box">
                <input type="submit" name="submit" value="Log in" class="btn btn-primary" id="submit-id-submit">
            </div>
        </form>
        <!--[if lt IE 7]>
        <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Consider upgrading your browser</a> to better experience this site.</p>
        <![endif]-->
    </div>
</div>
{% endblock %}

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/login_base.html
{% extends "sail_frontend_app/base.html" %}

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/logout.html
{% extends "sail_frontend_app/login_base.html" %}

{% block content %}
<div class="row-fluid">
    <div>
        <p><span>You have been logged out.</span></p>
        <p><a href="{% url 'sail_frontend_app:login' %}">Login</a></p>
    </div>
</div>
{% endblock %}

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/navigation_bar.html
<div class="navbar navbar-static-top" style="margin: -1px -1px 0;">
    <div class="navbar-inner">
        <div class="container" style="width: auto; padding: 0 20px;">
            <a class="brand" href="#">Sail</a>
            <ul class="nav" ng-init="tab.display='reservation'">
                {# <!-- <li><a href="#">Home</a></li> --> #}
                <li ng-class="{active: tab.display=='reservation'}" ng-click="tab.display='reservation'"><a href="#/reservations">Reservations</a></li>
                <li ng-class="{active: tab.display=='property'}" ng-click="tab.display='property'"><a href="#/properties">Properties</a></li>
                <li ng-class="{active: tab.display=='calendar'}" ng-click="tab.display='calendar'"><a href="#/calendar">Calendar</a></li>
                <li ng-class="{active: tab.display=='report'}" ng-click="tab.display='report'"><a href="#/reports">Reports</a></li>
            </ul>
            <ul class="nav pull-right">
                <li><a href="#/account">Account</a></li>
                <li><a href="#/account">Help</a></li>
                <li class="divider-vertical"></li>
                <li><a href="{% url 'sail_frontend_app:logout' %}">Logout</a></li>
            </ul>
        </div>
    </div>
</div>

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/properties_tab.html
{# <!-- Properties buttons --> #}
<div>

<div ng-controller="CreatePropertyCtrl">
    <a class="btn" href="#" style="float:left" ng-click="openCreatePropertyModal()">
        <i class="icon-plus"></i> Add Properties
    </a>
</div>

<div style="float:left; padding:5px"></div>
<form style="float:left; margin:0px">
    <div class="input-append">
        {#<!-- Add the search-query and search-form classes for rounded corners -->#}
        <input type="text" class="span2">
        <button type="submit" class="btn">Search</button>
    </div>
</form>
<div class="clearfix"></div>
</div>

{# <!-- Two panes layout --> #}
<div class="row-fluid">
    {# <!-- List of reservations --> #}
    <div class="span6" style="word-wrap:break-word">
        <div ng-controller="PropertyCtrl">
            <div class="row-fluid" ng-repeat="property in properties" ng-click="selectProperty(property)">
                {% verbatim %}
                <div class="span4">{{property.name}}</div>
                <div class="span4">{{property.description}}</div>
                {% endverbatim %}
            </div>
        </div>
    </div>
    {# <!-- Selected property details --> #}
    <div class="span6">
        <div ng-controller="PropertyDetailCtrl">
        <div class="row">
        <div class="span4 offset4">
            <a class="btn btn-primary" href="#" ng-click="open()"><i class="icon-pencil"></i> Edit Property</a>
        </div>
        <div class="span4" ng-controller="CreateReservationCtrl">
            <a class="btn btn-primary" href="#" ng-click="openCreateReservationModal()"><i class="icon-plus"></i> Add Reservation</a>
        </div>
        </div>
        
        {% verbatim %}
        <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd>{{data.property.name}}</dd>

            <dt>Description</dt>
            <dd>{{data.property.description}}</dd>
            
            <dt>Currency</dt>
            <dd>{{data.property.currency}}</dd>
        </dl>
        {% endverbatim %}
        </div>
    </div>
</div>

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/reports_tab.html
<div>
<h4>Reports</h4>
</div>

<div class="row-fluid">
    <div class="span12" style="word-wrap:break-word">
        <div ng-controller="ReportCtrl">
        
            <form class="form-inline">
            
                <div class="control-group"
                    ng-class="{info: !selectedProperty.property.name, success: selectedProperty.property.name}"
                    style="display:inline-block">
                    <div class="controls" style="margin-left: 5px;">
                        <select ng-model="selectedProperty.property" ng-options="property as property.name for property in propertyList">
                            <option value="" disabled selected>-- Choose a property --</option>
                        </select>
                    </div>
                </div>
                
                <div class="control-group"
                    ng-class="{info: selectedProperty.property.name && !report.type.name, success: report.type.name}"
                    style="display:inline-block">
                    <div class="controls" style="margin-left: 5px;">
                        <select ng-model="report.type" ng-options="type as type.name for type in reportTypeList">
                            <option value="" disabled selected>-- Report Type --</option>
                        </select>
                    </div>
                </div>
                
                <div class="control-group"
                    ng-class="{info: report.type.name && !report.date_from, success: report.date_from}"
                    style="display:inline-block">
                    <div class="controls" style="margin-left: 5px;">
                        From: <input type="text" placeholder="Enter date" datepicker-popup="yyyy-MM-dd" ng-model="report.date_from"/>
                    </div>
                </div>
                
                <div class="control-group"
                    ng-class="{info: report.date_from && !report.date_to, success: report.date_to}"
                    style="display:inline-block">
                    <div class="controls" style="margin-left: 5px;">
                        To: <input type="text" placeholder="Enter date" datepicker-popup="yyyy-MM-dd" ng-model="report.date_to" min="report.date_from"/>
                    </div>
                </div>
                
                <a class="btn" href="#" ng-class="{'btn-success': selectedProperty.property.name && report.type.name && report.date_from && report.date_to}" ng-click="loadReport()">
                    <i class="icon-list-alt"></i> &nbspGet Report!
                </a>
                
            </form>
            
        <div my-ui-chart="chartData" chart-options="chartOptions"></div>

        </div>
    </div>
</div>

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/reservations_tab.html
{# <!-- Reservations buttons --> #}
<div>
<a class="btn" href="#" style="float:left"><i class="icon-plus"></i> Add Reservation</a>
<div style="float:left; padding:5px"></div>
<form style="float:left; margin:0px">
    <div class="input-append">
        {#<!-- Add the search-query and search-form classes for rounded corners -->#}
        <input type="text" class="span2">
        <button type="submit" class="btn">Search</button>
    </div>
</form>
<div class="clearfix"></div>
</div>

{# <!-- Two panes layout --> #}
<div class="row-fluid">
    {# <!-- List of reservations --> #}
    <div class="span6" style="word-wrap:break-word">
        <div ng-controller="ReservationCtrl">
            <div class="row-fluid" ng-repeat="reservation in reservations" ng-click="selectReservation(reservation)">
                {% verbatim %}
                <div class="span4">{{reservation.name}}</div>
                <div class="span4">{{reservation.description}}</div>
                <div class="span2">{{reservation.date_from | date:'MM/dd/yyyy'}}</div>
                <div class="span2">{{reservation.date_to | date:'MM/dd/yyyy'}}</div>
                {% endverbatim %}
            </div>
        </div>
    </div>
    {# <!-- Selected reservation details --> #}
    <div class="span6">
        <div ng-controller="ReservationDetailCtrl">
        
            <div class="row">
                <div class="span8 offset4">
                    <a class="btn btn-primary" href="#" ng-click="open()"><i class="icon-pencil"></i> Edit Reservation</a>
                </div>
            </div>
            
            {% verbatim %}
            <dl class="dl-horizontal">
                <dt>Name</dt>
                <dd>{{data.reservation.name}}</dd>

                <dt>Description</dt>
                <dd>{{data.reservation.description}}</dd>
                
                <dt>Amount</dt>
                <dd>${{data.reservation.price}}</dd>
                
                <dt>From</dt>
                <dd>{{data.reservation.date_from | date:'MM/dd/yyyy'}}</dd>
                
                <dt>To</dt>
                <dd>{{data.reservation.date_to | date:'MM/dd/yyyy'}}</dd>
            </dl>
            {% endverbatim %}
        
        </div>
    </div>
</div>

apps/sail_frontend_app_app/sail_frontend_app/templates/sail_frontend_app/scripts.html
<!--[if lt IE 9]>
<script src="bower_components/es5-shim/es5-shim.js"></script>
<script src="bower_components/json3/lib/json3.min.js"></script>
<![endif]-->

<script src="bower_components/jquery/jquery.js"></script>
<script src="bower_components/jquery/jquery-migrate.js"></script>
<script src="bower_components/angular/angular.js"></script>

{# <!-- build:js scripts/modules.js --> #}
<script src="bower_components/angular-resource/angular-resource.js"></script>
<script src="bower_components/angular-cookies/angular-cookies.js"></script>
<script src="bower_components/angular-sanitize/angular-sanitize.js"></script>

<script src="bower_components/angular-ui-bootstrap/src/modal/modal.js"></script>
<script src="bower_components/angular-ui-bootstrap/src/transition/transition.js"></script>

<script src="bower_components/angular-ui-bootstrap/src/datepicker/datepicker.js"></script>
<script src="bower_components/angular-ui-bootstrap/src/position/position.js"></script>

<script src="bower_components/momentjs/moment.js"></script>
<script src="bower_components/moment-timezone/moment-timezone.js"></script>

<script src="bower_components/lodash/dist/lodash.js"></script>
<script src="bower_components/restangular/src/restangular.js"></script>
{# <!-- endbuild --> #}

{# <!-- build:js({.tmp,app}) scripts/scripts.js --> #}
<script src="scripts/app.js"></script>
<script src="scripts/controllers/main.js"></script>

{# <!-- third party libraries --> #}
<script src="scripts/third-party/jstz/jstz-1.0.4.min.js"></script>
<script src="scripts/third-party/moment-timezone-data/moment-timezone-data.js"></script>

{# <!-- utilities --> #}
<script src="scripts/services/dateUtils.js"></script>

{# <!-- reservations logic --> #}
<script src="scripts/controllers/reservation.js"></script>
<script src="scripts/controllers/reservationDetail.js"></script>
<script src="scripts/controllers/editReservationModal.js"></script>

<script src="scripts/controllers/createReservation.js"></script>
<script src="scripts/controllers/createReservationModal.js"></script>

<script src="scripts/services/restReservation.js"></script>
<script src="scripts/services/updateSelectedReservation.js"></script>
<script src="scripts/services/currentlySelectedReservation.js"></script>

{# <!-- properties logic --> #}
<script src="scripts/controllers/property.js"></script>
<script src="scripts/controllers/propertyDetail.js"></script>
<script src="scripts/controllers/editPropertyModal.js"></script>

<script src="scripts/controllers/createProperty.js"></script>
<script src="scripts/controllers/createPropertyModal.js"></script>

<script src="scripts/services/restProperty.js"></script>
<script src="scripts/services/updateSelectedProperty.js"></script>
<script src="scripts/services/currentlySelectedProperty.js"></script>

{# <!-- calendar logic --> #}
<script src="bower_components/fullcalendar/fullcalendar.js"></script>
<script src="bower_components/angular-ui-calendar/src/calendar.js"></script>

<script src="scripts/controllers/calendar.js"></script>

{# <!-- reports logic --> #}
<!--[if lt IE 9]><script src="bower_components/jqplot-bower/dist/excanvas.js"></script><![endif]-->
<script src="bower_components/jqplot-bower/dist/jquery.jqplot.js"></script>
<script src="bower_components/jqplot-bower/dist/plugins/jqplot.barRenderer.js"></script>
<script src="bower_components/jqplot-bower/dist/plugins/jqplot.categoryAxisRenderer.js"></script>
<script src="bower_components/jqplot-bower/dist/plugins/jqplot.canvasAxisTickRenderer.js"></script>
<script src="bower_components/jqplot-bower/dist/plugins/jqplot.canvasTextRenderer.js"></script>

<script src="scripts/controllers/report.js"></script>

<script src="scripts/directives/myUiChart.js"></script>

{# <!-- international currency support --> #}
<script src="bower_components/iso-4217-currency-codes-angular/src/iso-4217-currency-codes-angular.js"></script>

{# <!-- endbuild --> #}