apps/sail_login_app/sail_login/urls.py
"""
Use sail_login as the namespace when including those urls inside another urlpatterns:

    urlpatterns = patterns('',
        ...
        url(r'^auth/', include('sail_login.urls', namespace='sail_login'))
    )
"""

from django.conf.urls import patterns, url

urlpatterns = patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'sail_login/login.html', 'redirect_field_name': None}, name='login'),
    url(r'^logout/$', 'logout', {'template_name': 'sail_login/logout.html', 'redirect_field_name':None}, name='logout'),
)

apps/sail_login_app/sail_login/templates/sail_login/login.html
{% extends "sail_login/login_base.html" %}

{% block content %}
<div class="row-fluid">
    <div>
        <form action="{% url 'sail_login:login' %}" class=" form-inline" method="post">
            {% csrf_token %}
            <div id="div_id_username" class="clearfix control-group">
                <div class="controls">
                    <Label class="span4">Username:</label>
                    <input style="height: 25px" type="text" name="username" maxlength="100" autocapitalize="off" autocorrect="off" class="textinput textInput" id="id_username">
                </div>
            </div>
            <div id="div_id_password" class="clearfix control-group">
                <div class="controls">
                    <Label class="span4">Password:</label>
                    <input style="height: 25px" type="password" name="password" maxlength="100" autocapitalize="off" autocorrect="off" class="textinput textInput" id="id_password">
                </div>
            </div>
            <div class="form-actions-no-box">
                <input type="submit" name="submit" value="Log in" class="btn btn-primary" id="submit-id-submit">
            </div>
        </form>
    </div>
</div>
{% endblock %}

apps/sail_login_app/sail_login/templates/sail_login/login_base.html
{% load url from future %}
{% load static from staticfiles %}
<!DOCTYPE html>
<html>

    <head>
    {% block head %}

        {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        {% endblock %}

        <title>{% block title %}Sail App{% endblock %}</title>

        {% block style %}
        {% block bootstrap_theme %}
        <link rel="stylesheet" type="text/css" href="{% static "sail_login/css/bootstrap.css" %}"/>
        <link rel="stylesheet" type="text/css" href="{% static "sail_login/css/bootstrap-tweaks.css" %}"/>
        {% endblock %}
        <link rel="stylesheet" type="text/css" href="{% static "sail_login/css/default.css" %}"/>
        {% endblock %}
    {% endblock %}
    </head>

    <body class="container">

        <div class="container-fluid" style="margin-top: 30px">
            <div class="row-fluid">
                <div class="well" style="width: 320px; margin-left: auto; margin-right: auto">
                    <div class="row-fluid">
                        <div>
                            {% block branding %}<h3 style="margin: 0 0 20px;">Sail</h3>{% endblock %}
                        </div>
                    </div><!-- /row fluid -->
        
                    {% block content %}
                    {% comment %}<!-- login/logout content goes here -->{% endcomment %}
                    {% endblock %}
                    
                </div><!--/.well-->
            </div><!-- /.row-fluid -->
        </div><!-- /.container-fluid -->
    </body>
</html>

apps/sail_login_app/sail_login/templates/sail_login/logout.html
{% extends "sail_login/login_base.html" %}

{% block content %}
<div class="row-fluid">
    <div>
        <p><span>You have been logged out.</span></p>
        <p><a href="{% url 'sail_login:login' %}">Login</a></p>
    </div>
</div>
{% endblock %}